on:
  # schedule:
  # - cron: "0 2 * * 1-5"
  workflow_dispatch:
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Check curl version
        run: |
          curl --version
      - name: Check sqlite3 version
        run: |
          sqlite3 --version
