on:
  # schedule:
  # - cron: "0 2 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository 
        uses: actions/checkout@v3
      - name: Import IMDb tsv datasets into SQLite database and make release 
        run: |
          curl --version
          sqlite3 --version
          gunzip --version
      
          {
            echo "create table title_ratings (
              tconst text primary key,
              averageRating real not null,
              numVotes integer not null
            );"
            echo ".mode tabs"
            echo ".import ./title.ratings.tsv title_ratings"
            echo "select count(*) from title_ratings;"
          } > ./title.ratings.init.sql

          for d in title.ratings
          do
            time curl -s "https://datasets.imdbws.com/$d.tsv.gz" | gunzip > "./$d.tsv";
            wc -l "./$d.tsv";
            cat "$d.init.sql" | sqlite3 ./imdb.sqlite3
          done
          gh release upload latest ./imdb.sqlite3
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
