on:
  # schedule:
  # - cron: "0 2 * * 1-5"
  workflow_dispatch:
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: DO
        run: |
          curl --version
          sqlite3 --version
          gunzip --version
      
          {
            echo "create table title_ratings (
              tconst text primary key,
              averageRating real not null,
              numVotes integer not null
            );"
            echo ".mode tabs"
            echo ".import ./title.ratings.tsv title_ratings"
            echo "select count(*) as title_ratings_count from title_ratings;"
          } > ./title.ratings.init.sql

          for d in title.ratings
          do
            time curl -s "https://datasets.imdbws.com/$d.tsv.gz" | gunzip > "./$d.tsv";
            wc -l "./$d";
            cat "$d.init.sql" | sqlite3 ./imdb.db
          done
        shell: bash
